//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerADMProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Factura
    {
        public int FacturaID { get; set; }
        public int VehiculoID { get; set; }
        public short Cantidad { get; set; }
        public float Descuento { get; set; }
        public decimal Precio { get; set; }
    }
}
