//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerADMProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public int ID { get; set; }
        public int CategoriaID { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string Nochasis { get; set; }
        public string color { get; set; }
        public int NoPuertas { get; set; }
        public int Cilindros { get; set; }
        public int KilometrajeActual { get; set; }
        public System.DateTime AñoRegistro { get; set; }
        public Nullable<System.DateTime> FechaAdquisicion { get; set; }
        public string PrecioAdquirido { get; set; }
        public string PrecioVenta { get; set; }
        public string Detalles { get; set; }
        public string Pais { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
