//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerADMProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int ID { get; set; }
        public int VehiculoID { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public string PagoMensual { get; set; }
        public string PrecioAcordado { get; set; }
        public string PrecioVenta { get; set; }
        public string Comentario { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string Detalle { get; set; }
    }
}
